### PR TITLE
New Languages

### PR DESCRIPTION
**Pull request by Newspicel**
### Changes
Add ru
Add ar
Add sq

- [ ] New feature
- [ ] Bug fixes
- [ ] Documentation
- [x] Other: New Languages

### CODE REVIEW

**Comment by NicknameException** [comment]
Are these human translations or made using machine translation software? If so, is the use of it compatible to our license?

**Comment by Newspicel** [comment]
Is it created by a translation software. But this software has been paid for and only one mention is needed in the licence. So I have given the software as co-author and in File itself as co-author.

**Comment by NicknameException** [comment]
Let's see what @fbrettnich thinks

**Comment by fbrettnich** [comment]
Thank you for your interest in offering the bot in more languages.
Unfortunately, we cannot use the translations because the situation regarding the license and linking is too unclear.
In the future, please **only** submit **languages that you have translated yourself** or contact us via [discord](https://easypoll.me/discord) to **translate via our translation portal**.
We prefer to have bot translated by native speakers.

**Pull request closed without merging**
